QT.QCoroCore.VERSION = 0.12.0
QT.QCoroCore.MAJOR_VERSION = 0
QT.QCoroCore.MINOR_VERSION = 12
QT.QCoroCore.PATCH_VERSION = 0
QT.QCoroCore.name = QCoro6Core
QT.QCoroCore.module = QCoro6Core
QT.QCoroCore.defines = 
QT.QCoroCore.includes =  $$PWD/../../include/qcoro6/qcoro $$PWD/../../include/qcoro6/QCoro
QT.QCoroCore.private_includes =
QT.QCoroCore.libs = $$PWD/../../lib
QT.QCoroCore.depends =  core  QCoroCoro
QT.QCoroCore.module_config = staticlib
